# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5bc0e6b8e3d671deb00e7365ada4704c2395ea07c151e0881818720319d8046c9aac100f02ff9a295f987a036c583edfaa50fdc5c091becaa34978d1d7a8c314

test:
  secret_key_base: 280bc1a0aeeb15054164cba39356a39ed053ef652fc77b85b04f4503a6121013ee592f0d0aae0df25c96d2ac65c1f75f01a6e8e6dea19fce9e0e7e8263c0227e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
